/* Heroes & Deities TCG — card database + starters */
window.HD = window.HD || {};

HD.RARITY_WEIGHT = { C: 30, U: 24, R: 22, SR: 12, L: 8.5, M: 3.5 };

HD.CARDS = {
  "001": { id:"001", kind:"paragon", name:"Ares, God of Cinders", cost:0, power:5000, rarity:"L", tribe:"Ares Host", bloodline:"Olympian", element:"Ember",
    ability:"WAR GOD'S COMMAND — 2 Divine. Choose 1 Ember Character you control. It gains +1,000 Power until end of turn. If that Character attacks this turn, draw 1 card.",
    aura:"FIRE THROUGH BRONZE — Your Ares Host and Cyclopean Forge Characters gain +500 Power while attacking.",
    awaken:"BURNING HOST — 2 HP. When you have 2 HP or less, you may Awaken this Paragon. INFERNO AURA — Your Ember Characters gain +1,000 Power while attacking.",
    lore:"Olympus is not protected by marble. It is protected by those willing to burn for it." },
  "003": { id:"003", kind:"character", name:"Achilles, Spear of the Myrmidons", cost:5, power:5000, counter:2000, rarity:"L", tribe:"Ares Host", bloodline:"Demigod", element:"Ember",
    keywords:["CHARGE","BLOODLUST"],
    ability:"CHARGE — When this Character attacks, it gets +1,000 this battle. BLOODLUST — When it defeats a Character, draw 1.",
    lore:"The gods gave him strength. The Myrmidons gave him purpose." },
  "006": { id:"006", kind:"character", name:"Diomedes, Captain of Argos", cost:4, power:3500, counter:2000, rarity:"SR", tribe:"Ares Host", bloodline:"Hero", element:"Ember",
    keywords:["GUARD"], ability:"GUARD. Your other Ares Host Characters get +500 during your turn.", lore:"A god may start a war. A captain ends it." },
  "008": { id:"008", kind:"character", name:"Atalanta, Huntress of Arcadia", cost:3, power:3000, counter:1000, rarity:"R", tribe:"Ares Host", bloodline:"Hero", element:"Ember",
    keywords:["RUSH"], ability:"RUSH. May attack the turn it enters.", lore:"She outran every suitor. The arrow never did." },
  "015": { id:"015", kind:"character", name:"Hoplite of Ares", cost:1, power:2000, counter:1000, rarity:"C", tribe:"Ares Host", bloodline:"Hero", element:"Ember",
    keywords:["GUARD","FATE"], ability:"GUARD. FATE — When you lose HP during a battle, if this is in your hand it gets Counter +1,000 this battle.", lore:"Even the smallest hoplite can start a war." },
  "025": { id:"025", kind:"character", name:"Myrmidon Spearman", cost:2, power:2500, counter:1000, rarity:"R", tribe:"Myrmidons", bloodline:"Hero", element:"Ember",
    keywords:["RUSH","CHARGE"], ability:"RUSH. CHARGE — +1,000 this battle.", lore:"A short spear. A shorter argument." },
  "027": { id:"027", kind:"character", name:"Peltast of Ares", cost:1, power:1500, counter:1000, rarity:"U", tribe:"Ares Host", bloodline:"Hero", element:"Ember",
    ability:"COUNTER +1,000.", lore:"He throws what the fire leaves behind." },
  "031": { id:"031", kind:"event", name:"Wrath of Ares", cost:2, power:0, rarity:"R", tribe:"Ares Host", element:"Ember",
    ability:"Choose an opposing Character. It gets -3,000 Power this turn.", lore:"Ares does not knock. He enters." },
  "032": { id:"032", kind:"event", name:"March of the Myrmidons", cost:2, power:0, rarity:"R", tribe:"Ares Host", element:"Ember",
    ability:"Your Characters get +1,000 Power this turn.", lore:"The Myrmidons do not march. The earth yields." },
  "034": { id:"034", kind:"relic", name:"Helm of Ares", cost:2, power:0, rarity:"R", tribe:"Ares Host", element:"Ember",
    ability:"Attach to your Paragon. It gets +1,000 Power.", lore:"Warm long after the war is done." },
  "035": { id:"035", kind:"relic", name:"Xiphos of Hephaestus", cost:3, power:0, rarity:"SR", tribe:"Myrmidons", element:"Ember",
    ability:"Your Characters get +500 while attacking.", lore:"A fallen star, still arguing with the night." },
  "036": { id:"036", kind:"domain", name:"Throne of Ares", cost:2, power:0, rarity:"SR", tribe:"Ares Host", element:"Ember",
    ability:"Your Ember Characters gain +500 Power while attacking. You may control only one Domain.", lore:"The seat still smokes. The god still sits." },
  "037": { id:"037", kind:"mythic", name:"The Fall of Phaethon", cost:6, power:0, rarity:"M", tribe:"Ares Host", element:"Ember", finish:"holo",
    ability:"All opposing Characters get -2,000 Power this turn. You may rest your Paragon: if you do, also give your Paragon +2,000 this turn.", lore:"When a god's son falls, the world keeps the heat." },
  "039": { id:"039", kind:"event", name:"Edict of Ares", cost:1, power:0, rarity:"R", tribe:"Ares Host", element:"Ember",
    keywords:["FATE"], ability:"Draw 1. FATE — When you lose HP during a battle, if this is in your hand, your battling card gets +2,000 this battle.", lore:"The word of Ares is a second army." },
  "044": { id:"044", kind:"character", name:"Ember Phalanx", cost:2, power:2000, counter:1000, rarity:"C", tribe:"Ares Host", bloodline:"Hero", element:"Ember",
    keywords:["GUARD"], ability:"GUARD.", lore:"One shield is a man. A wall of them is a god's argument." },
  "045": { id:"045", kind:"event", name:"War Horn of Argos", cost:1, power:0, rarity:"U", tribe:"Ares Host", element:"Ember",
    ability:"Draw 1.", lore:"The horn does not ask. It gathers." },
  "046": { id:"046", kind:"character", name:"Myrmidon Shieldbearer", cost:2, power:2000, counter:1000, rarity:"C", tribe:"Myrmidons", bloodline:"Hero", element:"Ember",
    keywords:["GUARD"], ability:"GUARD.", lore:"The ant-men do not break. They lock." },
  "047": { id:"047", kind:"character", name:"Torchbearer of Ares", cost:1, power:1500, counter:1000, rarity:"U", tribe:"Ares Host", bloodline:"Hero", element:"Ember",
    keywords:["RUSH"], ability:"RUSH.", lore:"He runs so the war arrives first." },
  "002": { id:"002", kind:"paragon", name:"Brontes, God of the Thunderforge", cost:0, power:5000, rarity:"L", tribe:"Cyclopean Forge", bloodline:"Primordial God", element:"Ember",
    ability:"THUNDERFORGE — 3 Divine. Once per turn, rest 3 Divine: a Titanborn or Cyclopean Forge Character gets +1,000 this turn.",
    aura:"The hammer remembers every mountain it shaped.",
    awaken:"STORM OF ETNA — 2 HP. When you have 2 HP or less, you may Awaken this Paragon. HEART OF ETNA — Your Titanborn and Cyclopean Forge Characters gain +1,000 Power while attacking.",
    lore:"The mountains were not built before him. They were shaped by his hammer." },
  "004": { id:"004", kind:"character", name:"Cedalion, Heir of the Forge", cost:5, power:4500, counter:2000, rarity:"L", tribe:"Cyclopean Forge", bloodline:"Demigod", element:"Ember",
    keywords:["GUARD"], ability:"GUARD. When this Character enters, you may attach 1 Active Divine to it.", lore:"A weapon is only as true as the god who hammers it." },
  "020": { id:"020", kind:"character", name:"Aeacus, Warden of Chains", cost:4, power:3000, counter:2000, rarity:"SR", tribe:"Cyclopean Forge", bloodline:"Hero", element:"Ember",
    keywords:["GUARD"], ability:"GUARD.", lore:"The chains were never for prisoners. They were for the battlefield." },
  "021": { id:"021", kind:"character", name:"Pyracmon, Forge Warden", cost:4, power:4000, counter:1000, rarity:"R", tribe:"Cyclopean Forge", bloodline:"Hero", element:"Ember",
    keywords:["GUARD"], ability:"GUARD.", lore:"He does not raise walls. He raises the will to stand." },
  "028": { id:"028", kind:"character", name:"Cabiri Apprentice", cost:2, power:2000, counter:1000, rarity:"U", tribe:"Cyclopean Forge", bloodline:"Hero", element:"Ember",
    ability:"COUNTER +1,000.", lore:"The hammer is heavier than the lesson." },
  "029": { id:"029", kind:"character", name:"Bronze Aspis", cost:2, power:1500, counter:2000, rarity:"C", tribe:"Cyclopean Forge", bloodline:"Automaton", element:"Ember",
    keywords:["GUARD"], ability:"GUARD.", lore:"A shield that remembers every blow it took." },
  "038": { id:"038", kind:"relic", name:"Heart of Talos", cost:2, power:0, rarity:"R", tribe:"Cyclopean Forge", element:"Ember",
    ability:"Your Paragon gets +1,000 Power while being attacked.", lore:"It beats only when struck." },
  "040": { id:"040", kind:"domain", name:"Anvil of Etna", cost:2, power:0, rarity:"SR", tribe:"Cyclopean Forge", element:"Ember",
    ability:"Your Cyclopean Forge and Titanborn Characters gain +500 Power while attacking. You may control only one Domain.", lore:"The mountain is the anvil. The god is the hammer." },
  "041": { id:"041", kind:"mythic", name:"Thunderbolt of Brontes", cost:6, power:0, rarity:"M", tribe:"Cyclopean Forge", element:"Ember", finish:"foil",
    ability:"All opposing Characters get -2,000 Power this turn. You may rest your Paragon: if you do, also give your Paragon +2,000 this turn.", lore:"Zeus asked. Brontes answered in lightning." },
  "042": { id:"042", kind:"event", name:"Quench of Etna", cost:2, power:0, rarity:"R", tribe:"Cyclopean Forge", element:"Ember",
    ability:"Choose an opposing Character. It gets -2,000 Power this turn. Draw 1.", lore:"Hot bronze listens. Cold bronze commands." },
  "043": { id:"043", kind:"event", name:"Spark of the Cyclopes", cost:1, power:0, rarity:"U", tribe:"Cyclopean Forge", element:"Ember",
    ability:"Draw 1. You may attach 1 Active Divine to a Character you control.", lore:"One spark. One mountain." },
  "050": { id:"050", kind:"character", name:"Etna Sentry", cost:2, power:2000, counter:1000, rarity:"C", tribe:"Cyclopean Forge", bloodline:"Automaton", element:"Ember",
    keywords:["GUARD"], ability:"GUARD.", lore:"The mountain posted a watch. The watch is bronze." },
  "051": { id:"051", kind:"character", name:"Steropes, Spark Titan", cost:3, power:3000, counter:1000, rarity:"R", tribe:"Cyclopean Forge", bloodline:"Titanborn", element:"Ember",
    keywords:["RUSH"], ability:"RUSH.", lore:"He does not light the forge. He is the light." },
  "052": { id:"052", kind:"character", name:"Arges, Bright Hammer", cost:3, power:2500, counter:1000, rarity:"R", tribe:"Cyclopean Forge", bloodline:"Titanborn", element:"Ember",
    keywords:["CHARGE"], ability:"CHARGE — When this Character attacks, it gets +1,000 this battle.", lore:"Every strike writes a new law in the metal." },
  "053": { id:"053", kind:"relic", name:"Hammer of Brontes", cost:3, power:0, rarity:"SR", tribe:"Cyclopean Forge", element:"Ember",
    ability:"Attach to a Character. It gets +1,000 Power and GUARD.", lore:"The tool outlived the mountain it was made to break." },
  "054": { id:"054", kind:"event", name:"Molten Geas", cost:2, power:0, rarity:"R", tribe:"Cyclopean Forge", element:"Ember",
    ability:"Your Characters get +1,000 Power this turn.", lore:"The oath is poured, not spoken." },
  "055": { id:"055", kind:"character", name:"Forge Hand", cost:1, power:1500, counter:1000, rarity:"C", tribe:"Cyclopean Forge", bloodline:"Hero", element:"Ember",
    ability:"COUNTER +1,000.", lore:"Someone must hold the tongs." },
  "056": { id:"056", kind:"character", name:"Lava Runner", cost:1, power:1500, counter:1000, rarity:"U", tribe:"Cyclopean Forge", bloodline:"Hero", element:"Ember",
    keywords:["RUSH"], ability:"RUSH.", lore:"He arrives with the heat still on the bronze." },
  "058": { id:"058", kind:"event", name:"Edict of the Forge", cost:1, power:0, rarity:"R", tribe:"Cyclopean Forge", element:"Ember",
    keywords:["FATE"], ability:"Draw 1. FATE — When you lose HP during a battle, if this is in your hand, your battling card gets +2,000 this battle.", lore:"The forge does not argue. It answers." }
};

HD.DIVINE = { id:"DIV", kind:"divine", name:"Divine Ember", cost:0, power:0, rarity:"C", tribe:"—", ability:"Resource. Rest to pay costs. Attach to raise Power by +1,000." };
function copies(id, n){ return Array.from({length:n}, () => id); }
HD.ST01 = { id:"ST-01", name:"Host of Ares", paragon:"001", main: [...copies("015",4), ...copies("044",5), ...copies("046",5), ...copies("027",4), ...copies("047",4), ...copies("045",4), ...copies("008",4), ...copies("025",3), ...copies("031",2), ...copies("032",2), ...copies("034",2), ...copies("039",2), ...copies("006",2), ...copies("035",2), ...copies("036",2), ...copies("003",2), "037"] };
HD.ST02 = { id:"ST-02", name:"Thunderforge", paragon:"002", main: [...copies("029",5), ...copies("050",5), ...copies("055",4), ...copies("028",4), ...copies("056",4), ...copies("043",4), ...copies("021",3), ...copies("051",2), ...copies("052",2), ...copies("038",2), ...copies("042",2), ...copies("054",2), ...copies("058",2), ...copies("020",2), ...copies("040",2), ...copies("053",2), ...copies("004",2), "041"] };
HD.PACK_POOL = Object.values(HD.CARDS).filter(c => c.kind !== "paragon");
HD.canFinish = (c) => c && (c.rarity === "M" || /ALT|SSR|PAR/.test(c.id) || c.kind === "mythic");
HD.hash = (s) => { let h=0; for (const ch of String(s)) h = ((h<<5)-h)+ch.charCodeAt(0)|0; return Math.abs(h); };
HD.finishOf = (c, seed) => { if (!HD.canFinish(c)) return null; if (c.finish) return c.finish; return HD.hash((seed||"") + c.id) % 2 === 0 ? "foil" : "holo"; };
